name: Clustering POC LPS
description: Segmentation through clustering, deployed using Streamlit.
author: Adrian Maulana M.
specification_version: 1.0
prototype_version: 2.0
date: "2024-03-24"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    kernel: python3
    cpu: 1
    memory: 2

  - type: start_application
    name: Streamlit App
    subdomain: streamlit
    script: cml/launch_app.py
    short_summary: Start Streamlit application
    environment_variables:
      TASK_TYPE: START_APPLICATION
